#!/bin/bash

#list in the "for loop", the scripts to run tests in subdirectories.

err=0

run()
{
  d=`dirname $1`
  s=`basename $1`
  echo "
Running test $1"
  (cd $d && bash $s)
  return $?
}

for i in \
 fast/Readme \
 ivoc/Random/Readme \
 infrastructure/Readme
do
    run $i
    if [ $? -ne 0 ] ; then
        err=1
    fi
done

if [ $err -eq 0 ] ; then
    echo "All tests successful"
else
    echo "One or more tests failed"
fi

exit $err
