#!/bin/bash

have_nrnpython=no
have_nrnmpi=no
if nrniv -nobanner -nogui -c 'nrnversion(6)' | grep nrnpython > /dev/null ; then
  have_nrnpython=yes
fi
if nrniv -nobanner -nogui -c 'nrnversion(6)' | grep paranrn > /dev/null ; then
  have_nrnmpi=yes
fi
export have_nrnpython
export have_nrnmpi

#list in "scripts", the scripts to run tests in subdirectories.
#list in "compare", the folders to execute comparison tests
#  for all the *.cmp files in those folders
#


scripts="
fast/Readme
infrastructure/Readme
"

if test $have_nrnpython = yes -a $have_nrnmpi = yes ; then
  scripts="nrniv/Parallel/dotests.sh $scripts"
fi

compare="
ivoc/Random ivoc/Pointer ivoc/Vector ivoc/Matrix
nrniv nrniv/NetCon nrniv/SaveState
nmodl nmodl/FOR_NETCONS nmodl/functiontable nmodl/LONGDIFUS
nmodl/order nmodl/WATCH
"


cmpprog=`pwd`/testutil/cmpdatfile

err=0

runscript()
{
  d=`dirname $1`
  s=`basename $1`
  echo "
Running test $1"
  (cd $d && bash $s)
  return $?
}

runcompare()
{
  d=$1
  echo "
Running cmpdatfile in $1"
  (cd $d && $cmpprog *.cmp)
  return $?
}

for i in $scripts ; do
    runscript $i
    if [ $? -ne 0 ] ; then
        err=1
    fi
done

for i in $compare ; do
    runcompare $i
    if [ $? -ne 0 ] ; then
        err=1
    fi
done

echo ""
if [ $err -eq 0 ] ; then
    echo "All tests successful"
else
    echo "One or more tests failed"
fi

exit $err
