#!/bin/bash

export NRNUNIT_USE_LEGACY=1

CURRENT_DIR=$(dirname $0)
sh "$CURRENT_DIR/testutil/clean"
sh neurondemo -c 'quit()'

have_nrnpython=no
have_nrnmpi=no
if nrniv -nobanner -nogui -c 'nrnversion(6)' | grep nrnpython > /dev/null ; then
  have_nrnpython=yes
fi
if nrniv -nobanner -nogui -c 'nrnversion(6)' | grep paranrn > /dev/null ; then
  have_nrnmpi=yes
fi
export have_nrnpython
export have_nrnmpi

#list in "scripts", the scripts to run tests in subdirectories.
#list in "compare", the folders to execute comparison tests
#  for all the *.cmp files in those folders
#


scripts="
${CURRENT_DIR}/fast/Readme
${CURRENT_DIR}/infrastructure/Readme
"

if [[ "$have_nrnpython" = yes ]] && [[ "$have_nrnmpi" = yes ]] ; then
  scripts="nrniv/Parallel/dotests.sh $scripts"
fi

compare="
ivoc/Random ivoc/Pointer ivoc/Vector ivoc/Matrix
nrniv nrniv/NetCon nrniv/SaveState
nmodl nmodl/FOR_NETCONS nmodl/functiontable nmodl/LONGDIFUS
nmodl/order nmodl/WATCH
nmodl/CONDUCTANCE
"


cmpprog="$CURRENT_DIR/testutil/cmpdatfile"

err=0

runscript()
{
  working_dir=$(dirname "$1")
  script=$(basename "$1")
  echo "
Running test $1"
  (cd "$working_dir" && bash "$script")
  return $?
}

runcompare()
{
  working_dir=$1
  echo "
Running cmpdatfile in $1"
  (cd "$working_dir" && "$cmpprog" *.cmp)
  return $?
}

for i in $scripts ; do
    runscript "$i"
    if [ $? -ne 0 ] ; then
        err=1
    fi
done

for i in $compare ; do
    runcompare "$CURRENT_DIR/$i"
    if [ $? -ne 0 ] ; then
        err=1
    fi
done

echo ""
if [ $err -eq 0 ] ; then
    echo "All tests successful"
else
    echo "One or more tests failed"
fi

exit $err
