#!/usr/bin/env bash

set -eu

if ! command -v nrnivmodl
then
    echo "nrnivmodl not found, please set it before running this script"
    exit 1
fi

nrnivmodl_path="$(command -v nrnivmodl)"
arch="$(sed -n '/^ARCH=/s/ARCH=//p' "${nrnivmodl_path}")"

for name in fast ivoc nmodl npy nrniv nrnoc thread
do
   find "${name}" -name "${arch}" -prune -exec rm -fr {} \;
done
