#!/bin/bash
#test harness for case when $1.hoc output is to be compared to $1.dat
err=0
for i in $* ; do
  # If the $i file contains the .hoc extension, remove it
  f=`echo $i | sed 's/.hoc$//'`
  nrniv -nogui -nobanner $f.hoc >& temp
  cmp $f.dat temp
  r=$?
  if [ $r = 0 ] ; then
      echo "$f.hoc succeeded"
  else
      echo "$f.hoc failed"
      err=1
  fi
done

exit $err

