#!/bin/bash
#test harness for case when $1.hoc output is to be compared to $1.cmp
err=0

# if mod file exists, run nrnivmodl
modfiles="`ls *.mod 2>/dev/null`"
if [[ -n "$modfiles" ]] ; then
  nrnivmodl >& /dev/null
  r=$?
  if [ $r != 0 ] ; then
    echo "nrnivmodl failed"
    exit 1
  fi
fi

# run the tests
for i in $* ; do
  # If the $i file contains the .hoc or .cmp extension, remove it
  f=`echo $i | sed 's/\.hoc$//
s/\.cmp$//'`
  nrniv -nogui -nobanner $f.hoc >& temp
  cmp $f.cmp temp
  r=$?
  if [ $r = 0 ] ; then
      echo "$f.hoc succeeded"
  elif [[ -e $f.cmp.c3 ]] && cmp $f.cmp.c3 temp ; then
      echo "$f.hoc succeeded"
  else
      echo "$f.hoc failed"
      err=1
  fi
done

exit $err

